Project List View
ece461l-fa24-final-project/hardwareby.us pull request #62
Opened 2024-10-29 00:49 UTC by ash3679

2024-11-06 22:29 UTC, nuudlman requested changes
Remove all files from the PR except for `components/ProjectList.tsx` and `styles/ProjectList.css`

2024-11-06 22:29 UTC, nuudlman commented on frontend/src/views/ProjectView.tsx
This is a different PR

2024-11-06 22:29 UTC, nuudlman commented on frontend/src/styles/ProjectView.css
Also a different PR

2024-11-06 22:29 UTC, nuudlman commented on frontend/src/components/ProjectList.tsx
> +]
Call the API instead of adding placeholder data

2024-11-08 07:43 UTC, DrewBritt approved these changes

2024-11-08 07:43 UTC, DrewBritt commented on frontend/src/components/ProjectList.tsx
> +}
This should probably moved to another file to be used by other components (ViewProject for example)

2024-11-08 15:07 UTC, nuudlman approved these changes
Yeah we'll need to refactor some things but this is good for now

2024-11-08 15:13 UTC, merged