Implemented Hardware Dialog component for checkin/out functionality
ece461l-fa24-final-project/hardwareby.us pull request #72
Opened 2024-11-05 00:33 UTC by XanderBonner

2024-11-05 14:37 UTC, nuudlman requested changes
Does this even need to be a dialog? I feel like it would be better if it was always displayed on the project page

2024-11-05 14:37 UTC, nuudlman commented on frontend/src/components/HardwareDialog.tsx
> +const HardwareDialog = ({ isOpen, onClose, onSubmit }: HardwareDialogProps) => {
Remember that this is a self-contained component, not a generic one like the user-form. So this shouldn't have any props, and should maintain all state internally and call the API itself

2024-11-05 14:37 UTC, nuudlman commented on frontend/src/components/HardwareDialog.tsx
> +    const [action, setAction] = useState<"checkOut" | "checkIn">("checkOut"); // Action state
Use an enum instead of stringly typing things

2024-11-05 14:37 UTC, nuudlman commented on frontend/src/components/HardwareDialog.tsx
> +export default HardwareDialog;
Remember that this should be inlined into the component declaration

2024-11-05 14:37 UTC, nuudlman commented on frontend/src/components/HardwareDialog.tsx
> +        if (isOpen) {
You should make isOpen a local `useState(false)`

2024-11-05 14:37 UTC, nuudlman commented on frontend/src/components/HardwareDialog.tsx
> +                    <button type="button" onClick={toggleAction}>
I don't think a toggle makes sense here, it seems perplexing for no reason. I would just make a button to checkin and a button to checkout, and grey them out if the request is impossible

2024-11-08 03:14 UTC, nuudlman requested changes
Looking good

2024-11-08 03:14 UTC, nuudlman commented on frontend/src/components/HardwareDialog.tsx
> +    CheckIn = "checkIn",
I think its just easier to duplicate the code rather than adding a bunch of complicated logic and state

2024-11-08 03:14 UTC, nuudlman commented on frontend/src/components/HardwareDialog.tsx
> +        const url = `/api/v1/projects/${projectId}/${hardwareId}/${action === ActionType.CheckOut ? "check-out" : "check-in"}?amount=${quantity}`;
Other than the previous comment on state, don't worry too much about the actual url for the API. The main thing missing here is the Auth header.

2024-11-08 03:14 UTC, nuudlman commented on frontend/src/components/HardwareDialog.tsx
> +        const url = `/api/v1/projects/${projectId}/${hardwareId}/${action === ActionType.CheckOut ? "check-out" : "check-in"}?amount=${quantity}`;
Also remember to URL encode things

2024-11-08 04:10 UTC, XanderBonner commented
Forgot to run prettier/lint. Ignore last push

2024-11-08 17:28 UTC, nuudlman approved these changes
LGTM

2024-11-08 17:28 UTC, merged