Get HardwareSets API
ece461l-fa24-final-project/hardwareby.us pull request #84
Opened 2024-11-11 21:31 UTC by DrewBritt

GET route ("/api/v1/hardware/[projectid]") that returns a JSON array of HardwareSet objects associated with a given projectid.

2024-11-11 21:56 UTC, DrewBritt commented
They're exposed to the client so we know which one they're actually trying to update; alternatively we can make the name field unique but that seems kinda silly. Any value they'd try to set in creation would just be ignored and handled by AUTOINCREMENT like you mentioned.

2024-11-11 22:01 UTC, nuudlman commented on backend/src/backend/router.gleam
> +            web.HardwareSet(-1, projectid, name, 100, 100),
Really the API for hardware.create_hardware_set should probably be projectid + name.

2024-11-11 22:01 UTC, nuudlman commented on backend/src/backend/router.gleam
> +            web.HardwareSet(-1, projectid, name, 100, 100),
Since the id of a hardware set isn't optional, but we are passing in a full hardware set to create one

2024-11-11 22:03 UTC, DrewBritt commented on backend/src/backend/router.gleam
> +    [projectid] -> {
We're getting a list of hardware sets associated with a given project, so we'd want to pass the projectid.

2024-11-14 01:45 UTC, nuudlman requested changes
A few nits, but I like whats happening here. I think we need to merge this before the other api one

2024-11-14 01:45 UTC, nuudlman commented on backend/src/backend/router.gleam
> +    [projectid] -> {
We should return the list of hardware sets associated with a projectid when you GET the projectid

2024-11-14 01:45 UTC, nuudlman commented on backend/test/backend_test.gleam
> +      [#("authorization", token)],
This API call should return the ID of the hardware set it created

2024-11-14 01:45 UTC, nuudlman commented on backend/src/backend/router.gleam
> +      }
You can just use wisp.required_method(http.Get)

2024-11-15 01:26 UTC, nuudlman approved these changes
LGTM

2024-11-15 01:26 UTC, merged